services:

  db:
    image: postgres:18
    container_name: helpdesk_postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql


  web:
    build: .
    container_name: helpdesk_api
    restart: unless-stopped

    command: sh -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn config.wsgi:application --bind 0.0.0.0:8000"

    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}

      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

      SECURE_SSL_REDIRECT: ${SECURE_SSL_REDIRECT}
      SECURE_HSTS_SECONDS: ${SECURE_HSTS_SECONDS}
      SECURE_HSTS_INCLUDE_SUBDOMAINS: ${SECURE_HSTS_INCLUDE_SUBDOMAINS}
      SECURE_HSTS_PRELOAD: ${SECURE_HSTS_PRELOAD}
      SESSION_COOKIE_SECURE: ${SESSION_COOKIE_SECURE}
      CSRF_COOKIE_SECURE: ${CSRF_COOKIE_SECURE}

    expose:
      - "8000"

    depends_on:
      - db


  nginx:
    image: nginx:alpine
    container_name: helpdesk_nginx
    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./staticfiles:/app/staticfiles:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro

    depends_on:
      - web


volumes:
  postgres_data: